export const EVENTS_LIST_REQUEST = "EVENTS_LIST_REQUEST";
export const EVENTS_LIST_SUCCESS = "EVENTS_LIST_SUCCESS";
export const EVENTS_LIST_FAIL = "EVENTS_LIST_FAIL";

export const EVENTS_CREATE_REQUEST = "EVENTS_CREATE_REQUEST";
export const EVENTS_CREATE_SUCCESS = "EVENTS_CREATE_SUCCESS";
export const EVENTS_CREATE_FAIL = "EVENTS_CREATE_FAIL";

export const EVENTS_UPDATE_REQUEST = "EVENTS_UPDATE_REQUEST";
export const EVENTS_UPDATE_SUCCESS = "EVENTS_UPDATE_SUCCESS";
export const EVENTS_UPDATE_FAIL = "EVENTS_UPDATE_FAIL";

export const EVENTS_DELETE_REQUEST = "EVENTS_DELETE_REQUEST";
export const EVENTS_DELETE_SUCCESS = "EVENTS_DELETE_SUCCESS";
export const EVENTS_DELETE_FAIL = "EVENTS_DELETE_FAIL";